//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules_classes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Channel
    {
        public Channel()
        {
            this.Clients = new HashSet<Client>();
            this.Added_date = DateTime.Now;
        }
    
        [Key]
        public int Channel_id { get; set; }

        [Required]
        public string Name { get; set; }

        public Nullable<System.DateTime> Added_date { get; set; }

        [ForeignKey("AspNetUsers")]
        public string Added_by { get; set; }

        [NotMapped]
        public string Added_by_name { get; set; }

        public virtual ICollection<Client> Clients { get; set; }
    }
}
