//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules_classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Stage_id { get; set; }
        public Nullable<int> Client_id { get; set; }
        public Nullable<bool> Is_joined { get; set; }
        public string Added_by { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
        public string Notes { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
