//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules_classes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Semester
    {
        public Semester()
        {
            this.Orders = new HashSet<Order>();
        }
    
        [Key]
        public int Semester_id { get; set; }
        
        [Required]
        public string Code { get; set; }
        
        public string Title { get; set; }
        
        public Nullable<bool> Is_active { get; set; }

        [ForeignKey("AspNetUsers")]
        public string Added_by { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
