//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules_classes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Service
    {
        public Service()
        {
            this.Order_services = new HashSet<Order_services>();
        }
    
        [Key]
        public int Service_id { get; set; }
        
        [Required]
        public string Name { get; set; }
        
        public Nullable<decimal> Price { get; set; }
        
        [ForeignKey("AspNetUsers")]
        public string Added_by { get; set; }
        
        public Nullable<System.DateTime> Added_date { get; set; }
    
        public virtual ICollection<Order_services> Order_services { get; set; }
    }
}
