//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules_classes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Worker
    {
        public Worker()
        {
            this.Order_workers = new HashSet<Order_workers>();
        }
    
        [Key]
        public int Worker_id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        [ForeignKey("AspNetUsers")]
        public string Added_by { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Order_workers> Order_workers { get; set; }
    }
}
